<h1>Editor článkov</h1>

<form method="post">
    <input type="hidden" name="article_id" value="<?= $article['article_id'] ?>" />
    Titulka<br />
    <input type="text" name="article_title" value="<?= $article['article_title'] ?>" /><br />
    URL<br />
    <input type="text" name="article_url" value="<?= $article['article_url'] ?>" /><br />
    Popis<br />
    <input type="text" name="article_description" value="<?= $article['article_description'] ?>" /><br />
    Klúčové slová<br />
    <input type="text" name="article_key_words" value="<?= $article['article_key_words'] ?>" /><br />
    <textarea name="article_content"><?= $article['article_content'] ?></textarea>
    <input type="submit" value="Uložiť článok" />
</form>

<script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea[name=article_content]",
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
        entities: "160,nbsp",
        entity_encoding: "named",
        entity_encoding: "raw"
    });
</script>