<!DOCTYPE html>
<html lang="sk-sk">
<head>
    <base href="http://kovko.yweb.sk" />
    <meta charset="UTF-8" />
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $keywords ?>" />
    <link rel="stylesheet" href="styles/style.css" type="text/css"/>
</head>

<body>
<header>
    <h1>Kovko - presentation web</h1>
</header>
<?php foreach ($sysMessage as $message) : ?>
    <p class="sysMessage"><?= $message ?></p>
<?php endforeach ?>
<nav>
    <ul>
        <li><a href="article/uvod">Úvod</a></li>
        <li><a href="article">Články</a></li>
        <li><a href="contact">Kontakt</a></li>
    </ul>
</nav>
<br clear="both" />

<article>
    <?php
        $this->controller->writeView();
    ?>
</article>

<footer>
    <p>test site</p>
</footer>
</body>
</html>